

class Constants {
    BASEURL = "https://5element.by/"
    OPENACARTPAGE = "https://5element.by/cart"
    IVALIDPASSWORD = "sdfsdfsdf"
    INVALIDLOGIN = "sdfsfdsf"
    VALIDPASSWORD = "MoiParol"
    VALIDLOGIN = "shymchonak.s@gmail.com"
    FIRSTNAME = "Ivan"
    LASTNAME = "Ivanov"
    PHONE = "33000000"
    MAXPRICEOFPRODUCT = "500"
    WARNINGNOTIFICATIONWITHINVALIDCREDENTIALS = "Некорректный ввод"
    NUMBEROFCOMPARINGPODUCTS = "2"
    TITLEOFMODALPOPUPLOGOIN = "Вход в аккаунт"
    INVALIDSEARCHKEYWORD = "sdfsdfsdfsdfsdfsdf"
    VALIDSEARCHKEYWOWRD = "пылесос"
    PROMOTIONSCATOGORY = "1"
    SMARTPHONESCATEGORY = "2"
    TELEVISONCATRGORY = "3"
    VACUUMCLEANERSCATEGORY = "4"
    WASHINGMACHINESCATEGORY = "5"
    REFRIGERATORSCATEGORY = "6"
    MICROWAVECATEGORY = "7"
    HEADPHONESCATEGORY = "8"
    ELECTRICKETTLESCATEGORY = "9"
    BLENDERSCATEGORY = "10"
    GARDENTRIMERSCATEGORY = "11"
    NUMBEROFADDEDPRODUCTS = "1"
    ALLPROMOTIONCATEGORY = "0"
    MAINPROMOTIONCATEGORY = "1"
    INSTALLMENTPLAPROMOTIONCATEGORY = "2"
    SALESPROMOTIONCATEGORY= "3"
    GIFTSPROMOTIONCATEGORY ="4"
    TITLEOFPERSONALAREA = "Личный кабинет"
    TITLEOFFAVORITEPAGE = "Избранное"
    TITLEOFEMPTYFAVORITEPAGE = "У нас столько замечательных товаров,\n" +
        "а в Избранном у Вас – пусто :(\n" +
        "Перейти в каталог"
    THEREISNOTHINGTOCOMPARE = "Пока не добавлено ни одного товара для сравнения"
    EMPTYCARTTITLE = "В корзине еще нет товаров"
    NOTIFICATIONWHENTHESAMEPRODUCTADDEDTWICE = "Товар уже в корзине, вы хотите добавить еще одну единицу товара?"
}

module.exports = new Constants();